id: kubestellar-cluster-plugin
name: KubeStellar Cluster Management
version: 1.0.0
description: Plugin for cluster onboarding and detachment operations with real functionality
author: CNCF LFX Mentee
compatibility:
  kubestellar: '>=0.21.0'
  go: '>=1.21'
endpoints:
  - path: /onboard
    method: POST
    handler: OnboardClusterHandler
  - path: /detach
    method: POST
    handler: DetachClusterHandler
  - path: /status
    method: GET
    handler: GetClusterStatusHandler
dependencies:
  - kubectl
  - clusteradm
permissions:
  - cluster.read
  - cluster.write